### ISSUE TITLE
Unable to Render v0.7.0 with Asterisk

### ISSUE THREAD

**Issue by pta200** [onsip/sipjs.com#16]
I seem to only be able to hear audio only by passing an audio element not an options object on my invite. Am I missing something or is there an issue with the options object?

So this doesn't work:
var media_options = {
        media: {
            constraints: {
                audio: true,
                video: false
            },
            render: {
                remote: document.getElementById('remoteAudio'),
                local:  document.getElementById('localAudio')
            }
        }
};
var session = UA.invite(document.getElementById('destination').value,media_options);

But this does:
var session = UA.invite(document.getElementById('destination').value,document.getElementById('remoteAudio'));

**Comment by joseph-onsip** [comment]
see https://groups.google.com/d/msg/sip_js/qaOqnreajrY/MaVpvwIDdaQJ
