### ISSUE TITLE
Document `hold` and `unhold`

### ISSUE THREAD

**Issue by wakamoleguy** [onsip/sipjs.com#17]
We're using proper re-INVITEs now, and so it is a good time to evaluate the browser landscape and see if `hold` and `unhold` are something that we can document into the actual public API.

**Comment by jlaine** [comment]
I'm wondering whether this issue can be closed, since `hold` and `unhold` are currently documented. One thing which would be nice though: document the `localHold` attribute.

**Comment by james-criscuolo** [comment]
You are correct, will close. Our minor version (0.15.x) will be introducing autogenerated documentation, so I anticipate that will be documented if it is public, along with many other things.
