### ISSUE TITLE
Allow using a custom console

### ISSUE THREAD

**Issue by matthieusieben** [onsip/sipjs.com#18]
Some JS frameworks offer their own wrapper around `window.console` (i.e. Angular's $log).
It would be very convenient to be able to tell SIP.js which `console` object to use when trying to print messages.

**Comment by matthieusieben** [comment]
Wrong project i believe. Will republish at the right place. Sorry.

**Comment by joseph-onsip** [comment]
https://github.com/onsip/SIP.js/issues/229
