### ISSUE TITLE
SIPJS Demo Call hangup automatically  

### ISSUE THREAD

**Issue by murugannode** [onsip/sipjs.com#19]
SIPJS(0.7.1) demo phone call(audio/video)  hangup automatically after 60 seconds,using with freeswitch

**Comment by egreenmachine** [comment]
I believe our demo phone uses 0.7.0. Additionally we use FreeSWITCH at OnSIP and are not experiencing this issue. I believe it is a problem with your FreeSWITCH config. Please follow up on our [mailing list](https://groups.google.com/forum/#!forum/sip_js) for more help.

**Comment by murugannode** [comment]
http://sipjs.com/download/sip-0.7.1.js if i use 0.7.0 no issue,but when i use sipjs demo phone(browser) i am facing this issue because demo phone (0.7.1)

**Comment by lylepratt** [comment]
We are actually experiencing this issue as well with 0.7.2
