### ISSUE TITLE
Subscription's `failed` event is undocumented

### ISSUE THREAD

**Issue by josephfrazier** [onsip/sipjs.com#20]
While investigating https://github.com/onsip/SIP.js/issues/247, I noticed that http://sipjs.com/api/0.7.0/subscription/ doesn't mention the `failed` event, which is emitted at: https://github.com/onsip/SIP.js/blob/0.7.1/src/Subscription.js#L263

**Comment by matthieusieben** [comment]
If you look at the return type of [UA.subscribe](http://sipjs.com/api/0.7.0/ua/#subscribetarget-event-options), you'll see that subscriptions implement both [SIP.Subscription](http://sipjs.com/api/0.7.0/subscription/) and [SIP.ClientContext](http://sipjs.com/api/0.7.0/context/client/). The latter of which *does* document the `failed` event. However, there is indeed a missmatch between the doc and the implementation, especially regarding the `rejected` event:
> rejected
> Fired each time an unsuccessful final (300-699) response is received. Note: This will also emit a failed event.
The prototype of `Subscription` overrides `receiveResponse`, which is the method that would emit `rejected` messages, but this method only emits `failed`events, on a restricted set of `errorCodes` and not on any "unsuccessful final (300-699) response received".

**Comment by james-criscuolo** [comment]
This issue is no longer relevant, as our documentation is auto-generated from typescript. All events will be documented.
