### ISSUE TITLE
Demo broken in Chrome 47

### ISSUE THREAD

**Issue by josephfrazier** [onsip/sipjs.com#21]
(originally noticed by @etamme)

While the demo on the front page worked in Chrome Version 46.0.2490.86 (64-bit), Chrome Version 47.0.2526.73 (64-bit) shows the following console error when a "video" button is clicked:

```
NavigatorUserMediaError {}
constraintName: ""
message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."
name: "PermissionDeniedError"
__proto__: NavigatorUserMediaError
```

As https://goo.gl/Y0ZkNV vaguely suggests, [Chrome 47 disables `getUserMedia` for untrusted origins](https://nimblea.pe/monkey-business/2015/09/14/getusermedia-will-require-https-soon/). Since sipjs.com is currently hosted by Github Pages, we should be able to find more information here: https://github.com/isaacs/github/issues/156

**Comment by james-criscuolo** [comment]
A lot of changes since here, but the demo is fine on latest chrome.
