### ISSUE TITLE
Session's "dialog" event is undocumented

### ISSUE THREAD

**Issue by josephfrazier** [onsip/sipjs.com#23]
This was introduced in https://github.com/onsip/SIP.js/commit/a65fde7e52efc0f3e2f2c5ebc4d1d72055c4fe15, but is not mentioned at http://sipjs.com/api/0.7.0/session/#events

See https://github.com/onsip/SIP.js/issues/275 for an example of a problem that can be mitigated by using the "dialog" event.

**Comment by wakamoleguy** [comment]
It doesn't look like this is used internally, so I'd be okay with it being documented and added to the public API.  Do we currently document Dialogs at all, though?

**Comment by josephfrazier** [comment]
Hmm yeah, I don't see any Dialog documentation. Do you think we should have that first?

**Comment by wakamoleguy** [comment]
Probably, yeah.  The event handler passes a Dialog to the callback, so documenting the event with a unknown, custom object is not ideal.

**Comment by wakamoleguy** [comment]
That said, Dialog has been internal so far, so it's potentially a pain to transition it to a stable, public API.

**Comment by josephfrazier** [comment]
Heh, yeah, I guess it wouldn't be so friendly to just say "this returns a `Dialog`, you're on your own from here", and a link to the source code would barely be better. Perhaps we should document `Dialog` as _only_ having a `mediaHandler`, to keep the public API as small as possible?

Alternatively, fixing https://github.com/onsip/SIP.js/issues/275 would reduce the need for "dialog" event docs in the first place. However, since there's at least one other external use case for the event (mentioned in https://github.com/onsip/SIP.js/pull/134), I'm leaning towards documenting what's currently offered, then breaking the API if needed.

**Comment by james-criscuolo** [comment]
This event was removed
