### ISSUE TITLE
SIPjs can't get audio on chrome browser

### ISSUE THREAD

**Issue by haibui-htk** [onsip/sipjs.com#24]
Hi all, 

I have the problem with video/audio call with SIPjs client.
I use Kazoo system and create SIP account to make call.
First, I make call with audio (PCMU), it work ok.
After that, I enable video codec (VP8) for SIP user. Then make audio call (no video). I face the problem:
- I can not listen the audio from callee (receiver) 
- After that, I debug on Freeswitch and see: 
  + Caller make audio call with audio codec (PCMU) on SDP 
  + Freeswitch send Invite to callee with both audio codec (PCMU) and video codec (VP8). Because Kazoo see the callee support both video and audio codec. 
 + So that, callee make video + audio stream with Freeswitch. 

Some cases, I have tested:
+ Chrome call Chrome, Firefox call Chrome: Callee can't listen
+ Chrome call Firefox, Firefox call Firefox: Callee can listen ok
=> When call to Chrome, I see  chrome://webrtc-internals/ , the client can send/receive all packets but the audioOutputLevel of recevicer = 0 .

**Comment by james-criscuolo** [comment]
Hi @haibui-htk,
  This looks to be an issue with Freeswitch, considering an audio call comes in, and an audio/video call is offered out. Using a conditional dialplan or more sip profiles would probably fix this.

Also, this is not sip.js' [main repo](https://github.com/onsip/SIP.js), this is just for it's website, [sipjs.com](sip.js.com). This issue also does not belong in either repo, but you can try searching our [google group](https://groups.google.com/forum/#!forum/sip_js) for similar problems or posting there to see if anyone in the community has encountered this. Freeswitch also has some discussion boards and plenty of documentation, that may be the best place to start.

Thanks,
James

**Comment by haibui-htk** [comment]
Hi @james-criscuolo,
Thank for replying my topic.
I read the same topic on google group: https://groups.google.com/forum/#!topic/sip_js/8VsLxki1hGk
And work around with Freeswitch. But I really want to know: What problem with Chrome browser when Firefox work well ? You have any idea for this ?

**Comment by james-criscuolo** [comment]
Firefox and Chrome have different underlying webrtc implementations, although they are written to the same spec. Throughout my development with webrtc, I've found a lot of frustrating differences, with Firefox usually being slightly behind. It's nice to hear the problem is flipped, although it may just be because Chrome is doing something more inline with the spec, it's hard to say without digging deeper.
