### ISSUE TITLE
Switch between LTE and WIFI

### ISSUE THREAD

**Issue by shadmehr** [onsip/sipjs.com#26]
We use sip.js 0.7.5 for WebRTC on Cordova. It works fine with LTE and WiFi separately but after switching between LTE and WiFi, we lose the audio. We tried to close and unregister then reregister but we still get the same problem until we close the app and open it again. Is there a way to fix this issue? We also noticed that if I do that before first sip invite, we don't have the problem.

This is the log for the call on LTE. Destination answered and audio was fine.Then we switched to WiFi and called again.Destination answered but there was no audio.

[Issue4854-logs.txt](https://github.com/onsip/sipjs.com/files/274655/Issue4854-logs.txt)

**Comment by james-criscuolo** [comment]
Inappropriate place for this, sorry it wasn't closed earlier. As far as I know, there is still no good answer for this.
