### ISSUE TITLE
SetTypingDetectionStatus: not supported

### ISSUE THREAD

**Issue by cmendes0101** [onsip/sipjs.com#27]
I've been trying to add sipjs 0.7.5 into a webview on Android but can't seem to get it to run correctly. I am able to get it to run on Chrome desktop browser in jsfiddle fine but in the webview it can't get a audio stream. Comparing the logs this is what I see as different.

`
09-16 22:45:56.873 11689-11689/com.app.dev I/chromium: [INFO:CONSOLE(2884)] "Fri Sep 16 2016 22:45:56 GMT-0700 (PDT) | sip.invitecontext.mediahandler | acquired local media streams", source: file:///android_asset/scripts/sip-0.7.5.js (2884)
09-16 22:45:56.883 11689-12572/com.app.dev W/chromium: [WARNING:mediasession.cc(328)] Duplicate id found. Reassigning from 101 to 127
09-16 22:45:56.895 11689-12573/com.app.dev E/chromium: [ERROR:voe_audio_processing_impl.cc(955)] SetTypingDetectionStatus: not supported
09-16 22:45:56.896 11689-12573/com.app.dev W/chromium: [WARNING:webrtcvoiceengine.cc(817)] SetTypingDetectionStatus(0) failed, err=8003
09-16 22:45:56.905 11689-12573/com.app.dev E/chromium: [ERROR:voe_audio_processing_impl.cc(955)] SetTypingDetectionStatus: not supported
09-16 22:45:56.905 11689-12573/com.app.dev W/chromium: [WARNING:webrtcvoiceengine.cc(817)] SetTypingDetectionStatus(0) failed, err=8003
09-16 22:45:56.911 11689-12573/com.app.dev W/chromium: [WARNING:stunport.cc(393)] Jingle:Port[0x848f1c00:audio:1:0::Net[any:0:0:0:x:x:x:x:x/0:Unknown]]: StunPort: stun host lookup received error 0
09-16 22:45:56.914 11689-12573/com.app.dev W/chromium: [WARNING:stunport.cc(393)] Jingle:Port[0x848f2100:audio:2:0::Net[any:0:0:0:x:x:x:x:x/0:Unknown]]: StunPort: stun host lookup received error 0
`

`09-16 22:45:59.072 11689-12572/com.PrankRiot.dev E/chromium: [ERROR:webrtcsession.cc(1193)] SetAudioSend: No audio channel exists.`

The code in the activity:

`
WebView webView = (WebView) findViewById(R.id.webview);
                                                        webView.setWebViewClient(new WebViewClient());
                                                        webView.setWebChromeClient(new WebChromeClient() {

                                                            @Override
                                                            public void onPermissionRequest(final PermissionRequest request) {
                                                                Log.d(TAG, "onPermissionRequest");
                                                                mActivity.runOnUiThread(new Runnable() {
                                                                    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
                                                                    @Override
                                                                    public void run() {
                                                                        if(request.getOrigin().toString().equals("https://stream.demoapp.com/")) {
                                                                            request.grant(request.getResources());
                                                                        } else {
                                                                            request.deny();
                                                                        }
                                                                    }
                                                                });
                                                            }

                                                        });
                                                        webView.addJavascriptInterface(new WebViewInterface(getApplicationContext()), "Android");
                                                        webView.getSettings().setJavaScriptEnabled(true);
                                                        webView.loadUrl("file:///android_asset/html/index.html");`

index.html:
`<html>
<head>
    <script src="../scripts/sip-0.7.5.js"></script>
</head>
<body>
This is a test
<audio id="remoteAudio"></audio>

<script type="text/javascript">
    var session;
    var audioContext = new (window.AudioContext || window.webkitAudioContext)();
    var silentStream = audioContext.createMediaStreamDestination().stream;
    var userAgent = new SIP.UA({
        traceSip: true,
        uri: 'extension@stream.demoapp.com',
        wsServers: ['wss://stream.demoapp.com:8089/ws'],
        authorizationUser: 'user',
        password: '123456'
    });
    var options = {
        media: {
            stream: silentStream,
            constraints: {
                audio: true,
                video: false
            },
            render: {
                remote: document.getElementById('remoteAudio')
            }
        }
    };

    window.onload = function () {
        console.log(Android.getSipUri());
        session = userAgent.invite(Android.getSipUri(), options);
    }

</script>
</body>
</html>`

The devices I've tried are Nexus 6(5.1.1) and Nexus 5x(7.0). Does the error "SetTypingDetectionStatus: not supported" matter? Comparing with desktop Chrome that seems to be the only difference and I'm running Asterisk and the SIP traffic looks normal till client requests to close the connection when the above errors happen.

**Comment by egreenmachine** [comment]
I believe you meant to open an issue on SIP.js. This is just the repository for the website. This is really a question for our [mailing list](https://groups.google.com/forum/#!forum/sip_js).
