### ISSUE TITLE
Option to stop sending PRACKs

### ISSUE THREAD

**Issue by kirill-konshin** [onsip/sipjs.com#28]
In some systems PRACKs are not supported and lead to 4xx errors. 

PRACKs are covered by a separate RFC https://www.ietf.org/rfc/rfc3262.txt and are not a part of SIP RFC 3261. This RFC is focused on guaranteed establishing of a media session before 200OK. In RingCentral system there are no scenarios, which require a media session before the call is established. Moreover, most of SIP flows are built in an way where a leg is Answered before it any media is played.

With PRACKs calls are successfully established, but users get 4xx errors so the logs are not clean.

**Comment by egreenmachine** [comment]
I think you meant to open up an issue on [SIP.js](https://github.com/onsip/SIP.js). Either way turning off [100rel](http://sipjs.com/api/0.7.0/ua_configuration_parameters/#rel100) should stop your client from doing PRACK. 

I am going to close this issue. Feel free to follow up on [SIP.js](https://github.com/onsip/SIP.js) or the [mailing list](https://groups.google.com/forum/#!forum/sip_js).
