### ISSUE TITLE
Early Media and Hangup

### ISSUE THREAD

**Issue by telecmi** [onsip/sipjs.com#29]
I am using SIPJS for my webrtc client ,When i try to make call pstn, i  cant able to hear any early  media and if b leg (pstn) disconnect call ,A-leg(sipjs) did't receive bye message.

if i use this same scenario  in my voipfone(xlite,zoiper) works fine.

**Comment by adekock11** [comment]
Try the code here: https://github.com/onsip/SIP.js/issues/211
