### ISSUE TITLE
RTCIceChecking Timeout Triggered after 5000 milliseconds

### ISSUE THREAD

**Issue by habibshahid1** [onsip/sipjs.com#31]
I am having a strange problem and that only occurs when I make an outbound call. I tried using the SIP.js demo phone. When I dial an external number and the called party answers the call within 5 seconds then the media is established end to end but if the called party answers the call after 5 seconds then media from browser to asterisk is not established and its a one way audio call. Asterisk however plays MOH and DTMF.

Since the browser is running on https (self signed cert) the tcpdump on the server only traces the outside leg. Upon comparison I found no difference in signalling / SDP packets. Same was done at the client end browser. Signalling / SDP etc remains the same (or I wasn't able to find out) but SIP.js prints a log the says the following

------- in case of 1 way audio -------------
sip.js:36 Thu Aug 31 2017 19:02:11 GMT+0500 (Pakistan Standard Time) | sip.invitecontext.mediahandler | 5ht89pfuco7uopuuvnfvr6vgdksft0 | stream added: default
sip.js:36 Thu Aug 31 2017 19:02:16 GMT+0500 (Pakistan Standard Time) | sip.invitecontext.mediahandler | 5ht89pfuco7uopuuvnfvr6vgdksft0 | RTCIceChecking Timeout Triggered after 5000 milliseconds
sip.js:36 Thu Aug 31 2017 19:02:20 GMT+0500 (Pakistan Standard Time) | sip.transaction.ict | z9hG4bK3649713 | Timer B expired for INVITE client transaction z9hG4bK3649713
sip.js:36 Thu Aug 31 2017 19:02:28 GMT+0500 (Pakistan Standard Time) | sip.transport | received WebSocket text message:
---------------------------------------------
------- in case of successful call -------------
sip.js:36 Thu Aug 31 2017 18:43:42 GMT+0500 (Pakistan Standard Time) | sip.invitecontext.mediahandler | qotki1742sonfr93nuem74m4k726sf | stream added: default
sip.js:36 Thu Aug 31 2017 18:43:45 GMT+0500 (Pakistan Standard Time) | sip.transport | received WebSocket text message:
-------------------------------------------------
I am attaching the browser SIP Logs from the console if anyone can help me out.

[no-voice10.11.11.75-1504188160056.txt](https://github.com/onsip/sipjs.com/files/1277891/no-voice10.11.11.75-1504188160056.txt)
[10.11.11.75-1504187045459.txt](https://github.com/onsip/sipjs.com/files/1277892/10.11.11.75-1504187045459.txt)

I tried playing with iceCheckingTimeout but nothing helped. My UA looks like 

config : {
            password        : user.Pass,
            displayName     : user.Display,
            uri             : 'sip:'+user.User+'@'+user.Realm,
            wsServers       : user.WSServer,
            // stunServers : [],
            // usePreloadedRoute : true,
            registerExpires : 600,
            traceSip        : true,
		    hackWssInTransport: true,
		    hackIpInContact: true,
            log             : {
                level : 3,
            },
      	    rtcpMuxPolicy: "negotiate",
      	    iceCheckingTimeout: 500 // iceCheckingTimeout: 60000
        },

Any other logs required please let me know.

Thank you
Habib

**Comment by egreenmachine** [comment]
This is a problem with Asterisk. Feel free to ask on our [mailing list](https://groups.google.com/forum/#!forum/sip_js) or follow up with Asterisk.
