### ISSUE TITLE
Sipjs on commandline possible?

### ISSUE THREAD

**Issue by marlocarlo** [onsip/sipjs.com#35]
Hello,
Is it possible to use sip.js on the commandline? I would like to pipe video input from VLC/Ffmpeg and send it through sipjs. 

I have seen your nodejs code examples and your website mentions that it can be used inside the browser or within Nodejs but when I use it in Nodejs, how can I pass the process.stdin as the video input to the library?

Thanks,
Marlo

**Comment by james-criscuolo** [comment]
This question is better left to our mailing list. I would focus on how to get stdin into a MediaStream in Node.js, from there you can use a custom session description handler to use it.
