### ISSUE TITLE
Single line code examples are difficult to read and understand.

### ISSUE THREAD

**Issue by emahuni** [onsip/sipjs.com#37]
I don't understand why, but the code examples on sipjs.com are in one line and difficult to read in browser. I use Chrome, latest build and have downloaded Firefox and even tried it on Safari, but the result is the same. This package is great but this makes this very difficult to learn and wrap your head around since it's not easy to work with example code blocks.

However, not all code blocks are like that. Rarely code is displayed correctly as the following screenshots demonstrate. This is all on the same page: https://sipjs.com/guides/simple/ 

# It'd be great if all code appeared like this:

<img width="765" alt="Screenshot 2019-11-08 at 09 52 45" src="https://user-images.githubusercontent.com/7290508/68459269-953f3780-020d-11ea-979e-9836f380f2b8.png">

# instead of this: 

<img width="653" alt="Screenshot 2019-11-08 at 09 52 36" src="https://user-images.githubusercontent.com/7290508/68459286-a0926300-020d-11ea-9b3d-8186717c45ee.png">
 
# notice that I have to scroll the one liner to see the rest and the result isn't very pleasing nor useful:

<img width="658" alt="Screenshot 2019-11-08 at 09 57 06" src="https://user-images.githubusercontent.com/7290508/68459463-28786d00-020e-11ea-9454-ebbecbfe6d63.png">

# This not only makes it very difficult to copy example code for active learning purposes, but it's not easy to read what's written as well.

**Comment by emahuni** [comment]
for now I have actually decided to use the source to view the examples eg: https://github.com/onsip/sipjs.com/blob/master/content/guides/simple.md

**Comment by james-criscuolo** [comment]
This is now fixed, thanks for letting us know. Can't tell you why the line that was there used to work, or what changed to break it, but it's fixed now.

**Comment by emahuni** [comment]
great!
