### ISSUE TITLE
How do I get the same call id from freeswitch

### ISSUE THREAD

**Issue by emahuni** [onsip/sipjs.com#38]
I am trying to identify calls from Freeswitch using a socket event connection.
the idea is I want to log a call info into a DB that is independent of Freeswitch using an event socket connection, then associate it on the client side using some unique call id. The reason is I want to be able to use data in my application to log or manipulate it in many ways when a user misses, answers etc, a particular call since that call may never be intercepted by SIPjs (user might be offline). 

When a call comes in, the following Nodejs script intercepts an event and is given the call information:

```js
      const esl = require('modesl');
      const conn = new esl.Connection('192.168.43.5', 8021, 'ClueCon', function (ev) {
        conn.on('esl::**', function (evt) {
          console.debug(`index.js-50: () - evt: %o`, evt);
        });
      });
```

However, the `(_.find(evt.headers, {name: 'variable_sip_call_id'})).value ` in the headers of that event is different from the call id in sipjs `InviteServerContext.request.callId` (I just can't find the same value anywhere, I have checked other variables in the header). Here is an example:  

Freeswitch
```js
{
      name: 'variable_sip_call_id',
      value: '101921M2JjZTgyYzQ5YzE5ZDI0MWI3MmJlNTRkNWYzYzhjM2I'
    }
```

SIPjs
```js
{ callId: "a9590375-7fd2-1238-5bbd-f04da2cc571c"  }
```

How do I associate this call?

**Comment by emahuni** [comment]
I think you guys didn't do justice to this. Why did you label it as invalid? I was a newbie, i get it, but you could've corrected me or clarified what i was asking. I solved this then, but was just going thru my stuff when i noticed this closure and label you out on this issue.  

In freeswitch i had to export sip headers in the dialplan using `export`  `sip_h_X-callSID` then set the value as the call sid `${uuid}`.

In sipjs i then get the headers in the request headers as `X-Callsid`
Eg: `session.request.getHeader('X-Callsid')` which session is the InviteServerContext you get from an incoming call or invite `UA.on('invite', ...)`. 

This was simple help request that you closed and marked as invalid. There're a lot of questions about this without any help to it. I hope this helps someone.

**Comment by emahuni** [comment]
For call center you've to do`cc_export`

**Comment by egreenmachine** [comment]
This is marked as invalid because you are asking questions about SIP.js on the project for our website sipjs.com. Take a look at the [readme for this project](https://github.com/onsip/sipjs.com). Additionally if you did look into this project you will see that questions are answered on our [google group](https://groups.google.com/forum/#!forum/sip_js).

**Comment by emahuni** [comment]
Understood
